#!/bin/bash

# socialNetwork_post-storage-memcached - Sampling time: 5 minutes

# Record CPU cycles 
sudo perf record -j any_call,any_ret,save_type -e cpu-cycles -g -p <PID> -- sleep 300

# Record branch misses 
sudo perf record -j any_call,any_ret,save_type -e branch-misses,instructions -g -p <PID> -- sleep 300

# Record L1 instruction cache load misses 
sudo perf record -j any_call,any_ret,save_type -e L1-icache-load-misses,instructions -g -p <PID> -- sleep 300

# Record last-level cache load misses 
sudo perf record -j any_call,any_ret,save_type -e LLC-load-misses,instructions -g -p <PID> -- sleep 300


# socialNetwork_post-storage-mongodb 250686

# Record CPU cycles 
sudo perf record -j any_call,any_ret,save_type -e cpu-cycles -g -p <PID> -- sleep 300


# Record branch misses 
sudo perf record -j any_call,any_ret,save_type -e branch-misses,instructions -g -p <PID> -- sleep 300


# Record L1 instruction cache load misses 
sudo perf record -j any_call,any_ret,save_type -e L1-icache-load-misses,instructions -g -p <PID> -- sleep 300


# Record last-level cache load misses 
sudo perf record -j any_call,any_ret,save_type -e LLC-load-misses,instructions -g -p <PID> -- sleep 300
